# INDIAN OCEAN STOCK - MANAGEMENT ADVICE

**_Stock status_**. A new stock assessment was carried out for albacore in 2022 to update the assessment undertaken in 2019. The stock assessment was carried out using Stock Synthesis III (SS3), a fully integrated model that is currently also used to provide scientific advice for the three tropical tunas stocks in the Indian Ocean. The model used in 2022 is based on the model developed in 2019 with a series of revisions that were noted during the WPTmT data preparatory meeting held in January 2022. There are some noticeable changes compared to the previous assessment data set, mainly related to how the fisheries are structured, and how the CPUE indices and length composition data are treated within the assessment model.

The current assessment has utilised the new joint CPUE series that shows some differences compared with  the last assessment. This is mainly related to changes in standardisation methodology, which were partly caused by limited operational data access for joint CPUE analysis. Compared to the last assessment, the CPUE index in the south-western fishery (LL3) shows a somewhat flatter overall trend, the CPUE index in the north-western fishery (LL1) also exhibited considerably larger variability. Further, the size composition data are significantly down-weighted within the assessment model, and length samples from fisheries other than longline fisheries are effectively given a zero weight. This is to reduce the bias that can be introduced by potentially unrepresentative or problematic length samples.   

The final set of model options included alternative models using the northwest and southwest CPUE indices. Both sets of indices suggested a considerable difference in biomass trend between 1990 and now which highlights the uncertainty with respect to the model estimates of recent biomass trends. The two sets of indices effectively monitor different components of the albacore stock. The CPUE in the western area (LL1+3) may best represent the abundance of albacore at this time. The western area also represents a significant proportion of the albacore biomass in the Indian Ocean. The eastern indices are affected by changes in targeting.

Trends in the northwest CPUE series suggest that the biomass vulnerable to longline has declined to around 45-50% of the levels observed in 1980-82, whereas a much smaller decline was observed in the southwest CPUE series for the same period. Prior to 1980 there were 20 years of moderate fishing, after which total catches of albacore tuna in the Indian Ocean have more than doubled (**Fig. \@ref(fig:NCBarplots)**). Catches have also increased substantially since 2007 for some fleets (i.e., Indonesian and Taiwan,China longline fisheries), although there is substantial uncertainty regarding the reliability of the catch estimates. Catches in 2020 were marginally below the MSY level estimated by the SS3 model. Fishing mortality represented as F~2020~/F~MSY~ is 0.68 (0.42–0.94). Biomass is estimated to be above the SB~MSY~ level (1.56 (0.89–2.24)) from the SS3 model (**Table \@ref(tab:StatusTable)**, **Fig. 3**). These changes in stock status since the previous assessment are mainly due to changes in the CPUE. Thus, the stock status in relation to the Commission’s interim B~MSY~ and F~MSY~ target reference points indicates that the stock is **not overfished** and is not **subject to overfishing** (**Table \@ref(tab:StatusTable)**)[^1].

[^1]: only include last sentence if consistent with other species' ES

**_Outlook_**. The impacts of piracy in the western Indian Ocean resulted in the displacement of a substantial portion of longline fishing effort into the traditional albacore fishing areas in the southern and eastern Indian Ocean. However, in recent years the effort distribution in the Indian Ocean has been rather dynamic. Projections indicate that current catch appears to be sustainable in the short term although the projections are based on model assumptions that may be associated with high levels of uncertainty (see management advice below for more detail). It should be noted with caution that the short-term projections are more influenced by the recent low recruitment levels, whereas the long-term projections are more determined by the assumptions of average recruitment levels over the longer-term period.

**_Management advice_**. Although considerable uncertainty remains in the SS3 assessment conducted in 2022, particularly due to the conflicts in key data inputs, a precautionary approach to the management of albacore should be applied. The K2SM indicates that there is little risk of violating the target and limit reference points with current and moderate increases in catch in the short term. Current catches are just below the estimated level of MSY (`r pn(NC_LAST_YEAR)` t for the statistical year `r LAST_YEAR`; **Table 3**).

There remains considerable uncertainty resulting from changes in the CPUE series which are not well understood, model instability in response to updated data, growth variability and poor fits to the size data. It should be noted that neither CPUE series or other model assumptions account for any change in catchability/effort creep over the time series.

The following should be noted:

+ The primary sources of data that drive the assessment, total catches, CPUE and length data, are highly uncertain and should be developed further as a priority;

+ The catch estimates for 2020 (`r pn(NC_LAST_YEAR)` t) are above the current estimated MSY levels (**Table \@ref(tab:StatusTable)**);

+	A Kobe 2 Strategy matrix was calculated to quantify the risk of different future catch scenarios, using the projections from the SS3 model (**Table 3**);

+ Provisional reference points: noting that the Commission in 2015 adopted Resolution 15/10 On interim target and limit reference points and a decision framework, the following should be noted:

    - **Fishing mortality**: current fishing mortality is considered to be above the provisional target reference point of F~MSY~, but below the provisional limit reference point of 1.4\*F~MSY~ (**Fig. 3**)

    -	**Biomass**: current spawning biomass is considered to be above the target reference point of SB~MSY~, and therefore above the limit reference point of 0.4\*S~BMSY~ (**Fig. 2**)

+ **Main fisheries (mean annual catch `r paste(min(LAST_5_YEARS), max(LAST_5_YEARS), sep = "-")`)**: `r tolower(ES_SPECIES_INFORMATION$SPECIES)` are caught using `r NC_FISHERY_GROUP_RECENT_MEAN[1, tolower(FISHERY_GROUP)]` (`r NC_FISHERY_GROUP_RECENT_MEAN[1, PERCENT_CATCH]`%), followed by `r NC_FISHERY_GROUP_RECENT_MEAN[2, tolower(FISHERY_GROUP)]` (`r NC_FISHERY_GROUP_RECENT_MEAN[2, PERCENT_CATCH]`%) and `r NC_FISHERY_GROUP_RECENT_MEAN[3, tolower(FISHERY_GROUP)]` (`r NC_FISHERY_GROUP_RECENT_MEAN[3, PERCENT_CATCH]`%). The remaining catches taken with other gears contributed to `r NC_FISHERY_GROUP_RECENT_MEAN[4:nrow(NC_FISHERY_GROUP_RECENT_MEAN), sum(PERCENT_CATCH)]`% of the total catches in recent years (**Fig. \@ref(fig:NCBarplots)**).

+ **Main fleets (mean annual catch `r paste(min(LAST_5_YEARS), max(LAST_5_YEARS), sep = "-")`)**: the majority of `r tolower(ES_SPECIES_INFORMATION$SPECIES)` catches are attributed to vessels flagged to `r NC_FLEET_RECENT_MEAN[1, FLEET]` (`r NC_FLEET_RECENT_MEAN[1, PERCENT_CATCH]`%) followed by `r NC_FLEET_RECENT_MEAN[2, FLEET]` (`r NC_FLEET_RECENT_MEAN[2, PERCENT_CATCH]`%) and `r NC_FLEET_RECENT_MEAN[3, FLEET]` (`r NC_FLEET_RECENT_MEAN[3, PERCENT_CATCH]`%). The `r nrow(NC_FLEET_RECENT_MEAN) - 3` other fleets catching `r tolower(ES_SPECIES_INFORMATION$SPECIES)` contributed to `r  NC_FLEET_RECENT_MEAN[4:nrow(NC_FLEET_RECENT_MEAN), sum(PERCENT_CATCH)]`% of the total catch in recent years (**Fig. \@ref(fig:ParetoPlot)**).
