# Install/load libraries required for analysis
pacman::p_load(
  "tidyverse",
  "flextable",
  "scales",
  "openxlsx",
  "ggpubr",
  "gridExtra",
  "rmarkdown",
  "knitr",
  "bookdown",
  "officer",
  "png",
  "jpeg",
  "rvg",
  "officedown",
  "patchwork",
  "magick"
)